spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://10.1.30.205:3306/wh?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true
  redis:
      host: 10.1.30.210
      password: siti@sw
      port: 6379
      pool:
        max-active: 2000
        max-wait: 2000
        min-idle: 1
        max-idle: 100

logback:
  logHome: C:/wh/log/
  logName: wh

file:
  maxFileSize: 8388608  # 8* 1024 * 1024



