spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ITS@cai208
    url: jdbc:mysql://10.1.30.208:3306/wh?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true
  redis:
    host: 10.1.30.210
    password: wh@siti
    port: 6379
    pool:
      max-active: 2000
      max-wait: 2000
      min-idle: 1
      max-idle: 100


logback:
  logHome: C:/wh/log/
  logName: wh

sms:
   account_sid: 8a216da855826478015599e3f66e1411
   auth_token: 71a6619327734d81957e60f2eeaa2626
   appid: 8a216da86c8a1a54016c8dc74f1c0182
   serverip: app.cloopen.com
   serverport: 8883
   templateid: 462488
   flag: false