spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://10.1.30.205:3306/wh?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true

logback:
  logHome: /home/sq_data/log/
  logName: wh

file:
  maxFileSize: 8388608  # 8* 1024 * 1024



