spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: pdsw
    url: jdbc:mysql://172.20.50.115:3306/wh?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true
  redis:
      host: 172.20.50.115
      password: wh@siti
      port: 6379
      pool:
        max-active: 2000
        max-wait: 2000
        min-idle: 1
        max-idle: 100

logback:
  logHome: F:/PATH/wh/log/
  logName: wh


