server:
  port: 8080
  context-path: /sq

quartz:
  enabled: true
spring:
  thymeleaf:
    mode: LEGACYHTML5
  http:
    multipart:  # 文件上传
      enabled: true
      max-file-size: 50MB #单个数据大小
      max-request-size: 100MB #总数据大小
  profiles:
     active: prod
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

version:
  pcversion: "V1.1" # 版本号
  build: 1111 # 小版本号
